import { Request, Response, NextFunction } from 'express';
import { OrderExportService } from '../services/order_export.service.js';
import PDFDocument from 'pdfkit';

function getSummary(orders: any[]) {
  let totalRevenue = 0;
  let pendingCount = 0;
  let deliveredCount = 0;
  let cancelledCount = 0;
  let returnedCount = 0;

  orders.forEach((o) => {
    const amt = parseFloat(o.total || 0);
    if (o.status !== 'cancelled' && o.status !== 'delivery_failed') {
      totalRevenue += amt;
    }

    if (['placed', 'confirmed', 'packed', 'ready_for_pickup', 'shipped', 'out_for_delivery'].includes(o.status)) {
      pendingCount++;
    } else if (o.status === 'delivered') {
      deliveredCount++;
    } else if (o.status === 'cancelled') {
      cancelledCount++;
    } else if (
      [
        'return_requested',
        'return_approved',
        'returned_to_origin',
        'refund_requested',
        'refund_approved',
        'refunding',
        'refunded',
      ].includes(o.status)
    ) {
      returnedCount++;
    }
  });

  return {
    total: orders.length,
    pending: pendingCount,
    delivered: deliveredCount,
    cancelled: cancelledCount,
    returned: returnedCount,
    revenue: totalRevenue,
  };
}

export const exportOrdersPdf = async (req: Request, res: Response, next: NextFunction) => {
  try {
    if (!req.user || req.user.role !== 'admin') {
      return res.status(401).json({ success: false, message: 'Unauthorized session.' });
    }

    const filters = req.body;
    const orders = await OrderExportService.getFilteredOrders(filters);

    if (orders.length === 0) {
      return res.status(404).json({ success: false, message: 'No orders found for selected filters.' });
    }

    const summary = getSummary(orders);

    const doc = new PDFDocument({ margin: 30, size: 'A4' });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename=orders_report.pdf');
    doc.pipe(res);

    // Header
    doc.fontSize(20).text('Bezon Marketplace', { align: 'center' });
    doc.fontSize(14).text('Orders Report', { align: 'center' });
    doc.moveDown();

    // Metadata
    doc.fontSize(10).text(`Generated By: Admin (${req.user.id})`);
    doc.text(`Generated On: ${new Date().toLocaleString()}`);
    doc.text(`Total Records Exported: ${summary.total}`);
    doc.moveDown();

    // Applied Filters
    doc.fontSize(12).text('Applied Filters:', { underline: true });
    doc.fontSize(10);
    if (filters.searchTerm) doc.text(`Search: ${filters.searchTerm}`);
    if (filters.statusFilter) doc.text(`Status: ${filters.statusFilter}`);
    if (filters.paymentFilter) doc.text(`Payment: ${filters.paymentFilter}`);
    if (filters.sellerFilter) doc.text(`Seller: ${filters.sellerFilter}`);
    if (filters.partnerFilter) doc.text(`Partner: ${filters.partnerFilter}`);
    if (filters.customerFilter) doc.text(`Customer: ${filters.customerFilter}`);
    if (filters.startDate) doc.text(`Start Date: ${filters.startDate}`);
    if (filters.endDate) doc.text(`End Date: ${filters.endDate}`);
    if (Object.keys(filters).length === 0) doc.text('None');
    doc.moveDown();

    // Summary Section
    doc.fontSize(12).text('Summary:', { underline: true });
    doc.fontSize(10);
    doc.text(`Total Orders: ${summary.total}`);
    doc.text(`Total Order Value: INR ${summary.revenue.toFixed(2)}`);
    doc.text(`Delivered: ${summary.delivered}`);
    doc.text(`Pending: ${summary.pending}`);
    doc.text(`Cancelled: ${summary.cancelled}`);
    doc.text(`Returned: ${summary.returned}`);
    doc.moveDown();

    // Order Table
    doc.fontSize(12).text('Order List:', { underline: true });
    doc.moveDown();

    orders.forEach((o: any, i) => {
      doc.fontSize(10).text(`${i + 1}. ID: ${o.orderNumber || o.id.slice(0, 8)}`);
      doc.fontSize(9).text(`Customer: ${o.customer?.name} | Seller: ${o.seller?.shopName}`);
      doc.text(`Amount: INR ${o.total} | Payment: ${o.paymentStatus} | Status: ${o.status}`);
      doc.text(`Date: ${new Date(o.createdAt).toLocaleDateString()}`);
      if (o.delivery?.partner?.user?.name) {
        doc.text(`Partner: ${o.delivery.partner.user.name}`);
      }
      doc.moveDown(0.5);
    });

    doc.end();
  } catch (err) {
    next(err);
  }
};

export const exportOrdersCsv = async (req: Request, res: Response, next: NextFunction) => {
  try {
    if (!req.user || req.user.role !== 'admin') {
      return res.status(401).json({ success: false, message: 'Unauthorized session.' });
    }

    const filters = req.body;
    const orders = await OrderExportService.getFilteredOrders(filters);

    if (orders.length === 0) {
      return res.status(404).json({ success: false, message: 'No orders found for selected filters.' });
    }

    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', 'attachment; filename=orders_report.csv');

    // CSV Header
    let csv = 'Order ID,Customer Name,Seller Shop,Amount,Payment Status,Order Status,Created Date,Delivery Partner\n';

    // CSV Rows
    orders.forEach((o: any) => {
      const orderId = o.orderNumber || o.id.slice(0, 8);
      const cust = `"${(o.customer?.name || '').replace(/"/g, '""')}"`;
      const seller = `"${(o.seller?.shopName || '').replace(/"/g, '""')}"`;
      const amt = o.total;
      const pstatus = o.paymentStatus;
      const ostatus = o.status;
      const date = new Date(o.createdAt).toISOString();
      const partner = `"${(o.delivery?.partner?.user?.name || '').replace(/"/g, '""')}"`;

      csv += `${orderId},${cust},${seller},${amt},${pstatus},${ostatus},${date},${partner}\n`;
    });

    res.send(csv);
  } catch (err) {
    next(err);
  }
};
